### ISSUE TITLE
instalation fails on digital ocean for coreos 899

### ISSUE THREAD

**Issue by thomasmodeneis** [AndreyAntipov/kubernetes-coreos-do#1]
Hi,

I tried to make use of your script but it failed for me with the following errors, any ideas?

Master
```
CoreOS production (835.9.0)
Update Strategy: No Reboots
core@master ~ $ fleetctl list-machines
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
core@master ~ $ kubectl get nodes
-bash: kubectl: command not found
```

Node
```
CoreOS production (899.1.0)
core@node ~ $ fleetctl list-machines
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
core@node ~ $ kubectl get nodes
-bash: kubectl: command not found
```

**Comment by AndreyAntipov** [comment]
Hello Thomas

Just checked up this config on the last CoreOS build which are available on DO (899.1.0) and it's are work fine.

 Are you sure that you have enabled private networking?

Could you please provide some more details?

What binaries you have in /opt/bin?

How your cloud config is look like?
curl -w "\n" http://169.254.169.254/metadata/v1/user-data

You also can check syntax of this config here
https://coreos.com/validate/

Seems to be config didn't initialised completely, and stuck on etcd step.
